[versions]
agp = "9.0.0"
core = "1.18.0-alpha01"
appcompat = "1.7.1"
material = "1.14.0-alpha09"
constraintlayout = "2.2.1"
cardview = "1.0.0"
documentfile = "1.1.0"
recyclerview = "1.4.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

[libraries]
androidx-core = { group = "androidx.core", name = "core", version.ref = "core" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-cardview = { group = "androidx.cardview" , name = "cardview", version.ref = "cardview"}
androidx-documentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "documentfile"}
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview"}